language: node_js
branches:
  only:
    - master
node_js:
  - 10
services:
  - mysql
addons:
  apt:
    packages:
      # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
      - libgconf-2-4
cache:
  directories:
    - node_modules
    - server/node_modules
    - client/node_modules
    # we also need to cache folder with Cypress binary
    - ~/.cache
install:
  - npm run install-all
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
script:
  - npm run build
  - npm run test:ci
env:
  global:
    - NODE_ENV=test
    - DB_URL=mysql://root@127.0.0.1:3306/test
    - KEYGRIP_SECRETS="secret1 secret2 secret3"
    - SENDGRID="NotUsed"
    - npm_config_loglevel=silent
    - CI=false
